### ISSUE TITLE
Combine addon buttons not working and errors

### ISSUE THREAD

**Issue by Zergei** [Sattva-108/Leatrix_Plus#2]
![image](https://github.com/user-attachments/assets/f675b9a5-70c9-4b2e-96fa-41f437b43658)
this is what happens when you enable Combine addon buttons and also this errors when you set the scale

1x <unnamed>:SetScale(): Scale must be > 0:
<in C code>: ?
<in C code>: in function `SetScale'
Leatrix_Plus-3.3.5 (3.0.131)\Leatrix_Plus.lua:5214: in function <Leatrix_Plus\Leatrix_Plus.lua:5212>
<in C code>: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 t = <unnamed> {}
 f = <unnamed> {}
}
(*temporary) = -0.0099999964237213

  ---
  
  
  1x Leatrix_ButtonGrabber:SetScale(): Scale must be > 0:
<in C code>: ?
<in C code>: in function `SetScale'
Leatrix_Plus-3.3.5 (3.0.131)\Leatrix_Plus.lua:5201: in function `SetMinimapAddonButtonsFrameScale'
Leatrix_Plus-3.3.5 (3.0.131)\Leatrix_Plus.lua:5213: in function <Leatrix_Plus\Leatrix_Plus.lua:5212>
<in C code>: ?

Locals:
(*temporary) = Leatrix_ButtonGrabber {
 0 = <userdata>
}
(*temporary) = 0

  ---

2x <unnamed>:SetScale(): Scale must be > 0:
<in C code>: ?
<in C code>: in function `SetScale'
Leatrix_Plus-3.3.5 (3.0.131)\Leatrix_Plus.lua:5214: in function <Leatrix_Plus\Leatrix_Plus.lua:5212>
<in C code>: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 t = <unnamed> {}
 f = <unnamed> {}
}
(*temporary) = -0.070000000670552

  ---

2x <unnamed>:SetScale(): Scale must be > 0:
<in C code>: ?
<in C code>: in function `SetScale'
Leatrix_Plus-3.3.5 (3.0.131)\Leatrix_Plus.lua:5214: in function <Leatrix_Plus\Leatrix_Plus.lua:5212>
<in C code>: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 t = <unnamed> {}
 f = <unnamed> {}
}
(*temporary) = -0.040000001341105

  ---

**Comment by Sattva-108** [comment]
https://github.com/user-attachments/assets/1bf5aeb9-83d0-4288-a9d5-4b732febcb78


this is something that i cannot reproduce myself. 
it must be one of addons you have, that makes this conflict. 

if you ever have time to figure out which one please let me know

**Comment by Zergei** [comment]
> minimapButtons.mp4 
> this is something that i cannot reproduce myself. it must be one of addons you have, that makes this conflict.
> 
> if you ever have time to figure out which one please let me know

the problem is the addon button grabber is not hidding when i click it

**Comment by Sattva-108** [comment]
now i understand what's the problem, thank you for clarifying. 

problem is that this module had to be re-written from scratch and currently in alpha state.
i will try to implement the thing you need asap.

**Comment by Sattva-108** [comment]
currently i have to think how to solve this, as i already have minimap clicks bound:
1. Right Click - Show Tracking.
2. Middle click - Show Calendar. 

What i could do is probably make Calendar to be shown on Shift- Click

**Comment by Sattva-108** [comment]
Added the functionality you want, it now will be hidden on middle-click the minimap.
It will also remember if you have it hidden before logout / reload.

https://github.com/user-attachments/assets/8a97cccf-e2a0-4376-8f71-f217fd59cc5c

**Comment by Zergei** [comment]
ok ty for the update. sorry for not clarifying the issues. now since you stated that this version of leatrix is in alpha stage is possible to give you some recomendations to improve this addon?

**Comment by Sattva-108** [comment]
> ok ty for the update. sorry for not clarifying the issues. now since you stated that this version of leatrix is in alpha stage is possible to give you some recomendations to improve this addon?

sure, i'm open to suggestions

**Comment by Zergei** [comment]
ok so im using the recent release of leatrix and the button grabber still doesnt dissapear my guess is it has conflicts with "Atlas" addons (world globe icon) if you see the pic only the Addon atlas is not in the button grabber 
![image](https://github.com/user-attachments/assets/99a05f34-a859-4372-8ff3-704dac2bb6d7)

but the addon atlaslootfu it is inside (box icon)

**Comment by Sattva-108** [comment]
what happens if you middle-click the minimap? 

https://github.com/user-attachments/assets/755a62ee-1582-454d-952d-f47baa4939c7

**Comment by Zergei** [comment]
> what happens if you middle-click the minimap?
> 
>  middleclick.mp4

Minimap

**Comment by Zergei** [comment]
> what happens if you middle-click the minimap?
> 
>  middleclick.mp4

Calendar appears

**Comment by Sattva-108** [comment]
> > what happens if you middle-click the minimap?
> > middleclick.mp4
> 
> Calendar appears

then it means you have older version. Because calendar is now Shift+Click and middle click is for the Minimap Button grabber.
![wow_1VvissyW8M](https://github.com/user-attachments/assets/1fd00a19-b4e9-4a63-9fc8-be2f94bd4808)

**Comment by Zergei** [comment]
ok installed the new version of leatrix and works as supposed. ty for the help
